export const data = [
  {
    id: 1,
    pizza: "prosciutto",
    price: 10.99,
    vegetarian: false,
    img: "https://assets.zumepizza.com/public/j4lb8iry.jpg",
    description: "tomato sauce, cheese, ham",
    new: false,
    bestseller: true,
  },
  {
    id: 2,
    pizza: "happy pizza",
    price: 10.99,
    vegetarian: false,
    img: "https://assets.zumepizza.com/public/j4lb8iry.jpg",
    description: "tomato sauce, cheese, pepperoni, ham, paprika",
    new: false,
    bestseller: true,
  },
  {
    id: 3,
    pizza: "all-out pizza",
    price: 18.99,
    vegetarian: false,
    img: "https://assets.zumepizza.com/public/j4lb8iry.jpg",
    description: "every topping we have",
    new: false,
    bestseller: false,
  },
  {
    id: 4,
    pizza: "margherita",
    price: 10.99,
    vegetarian: true,
    img: "https://assets.zumepizza.com/public/j4lb8iry.jpg",
    description: "amko",
    new: false,
    bestseller: true,
  },
  {
    id: 5,
    pizza: "pepperoni",
    price: 12.99,
    vegetarian: false,
    img: "https://assets.zumepizza.com/public/j4lb8iry.jpg",
    description: "tomato sauce, cheese",
    new: false,
    bestseller: true,
  },
  {
    id: 6,
    pizza: "romana",
    price: 15.99,
    vegetarian: false,
    img: "https://assets.zumepizza.com/public/j4lb8iry.jpg",
    description: "tomato, mozzarella, anchovies, oregano, oil",
    new: false,
    bestseller: false,
  },
  {
    id: 7,
    pizza: "kebabpizza",
    price: 13.99,
    vegetarian: false,
    img: "https://assets.zumepizza.com/public/j4lb8iry.jpg",
    description: "döner kebab, onion, green peperoncini",
    new: true,
    bestseller: false,
  },
  {
    id: 8,
    pizza: "mexicana",
    price: 11.99,
    vegetarian: false,
    img: "https://assets.zumepizza.com/public/j4lb8iry.jpg",
    description:
      "minced beef, jalapeños, onion, spicy sauce and other spicy ingredients",
    new: false,
    bestseller: false,
  },
  {
    id: 9,
    pizza: "napolitana",
    price: 10.99,
    vegetarian: false,
    img: "https://assets.zumepizza.com/public/j4lb8iry.jpg",
    description: "anchovies, olives, capers",
    new: false,
    bestseller: false,
  },
  {
    id: 10,
    pizza: "quattro stagioni",
    price: 13.99,
    vegetarian: false,
    img: "https://assets.zumepizza.com/public/j4lb8iry.jpg",
    description: "ham, shrimp, (mussels), mushrooms, artichoke",
    new: true,
    bestseller: false,
  },
  {
    id: 11,
    pizza: "vegetariana",
    price: 12.99,
    vegetarian: true,
    img: "https://assets.zumepizza.com/public/j4lb8iry.jpg",
    description: "ham, shrimp, (mussels), mushrooms, artichoke",
    new: false,
    bestseller: false,
  },
];
